export const environment = {
 supabaseUrl: 'https://gtgumyuovlghwjslcppv.supabase.co',
 supabaseKey:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0Z3VteXVvdmxnaHdqc2xjcHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjE0ODk3MzIsImV4cCI6MjAzNzA2NTczMn0.krlp03YPyBlWush2F9dclfTwTEpJ4QpMTamPNAtIGOg'
};
